name: Playwright Tests

env:
      VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_API_KEY }}
      VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
on:
  push:
    branches: [ main, master ]
  pull_request:
     types: [opened, synchronize, closed]
     branches: [main, master]
jobs:
  deploy:
    if: ${{ github.event.action == 'opened' || github.event.action == 'synchronize' }}
    runs-on: ubuntu-latest
    steps:
      - uses: snaplet/vercel-action@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
          with:
        name: playwright-report
        path: playwright-report/
        retention-days: 15
  delete:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: snaplet/vercel-action@v2
        with:
          delete: true
  test:
    steps:

